# Travis-CI Build for flowgrind
# see travis-ci.org for details

language: c

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get -qq update

install:
    - sudo apt-get -qq install libxmlrpc-c3-dev libcurl4-gnutls-dev libpcap-dev libgsl0-dev

script:
    - autoreconf -i
    - ./configure && make

# Only watch the master and next branch
branches:
  only:
    - master
    - next

notifications:
  email:
    - developer@flowgrind.net
