# Travis-CI Build for flowgrind
# see travis-ci.org for details

env:
  global:
   # COVERITY_SCAN_TOKEN
    - secure: "VCugWaS9AjV7fCdXN28DNFspLYJjgphp4sP1785a0bA68hYggbPRjTQl2k3QNRpSMEJyAqjW4kSvDm5d8ndkpmSIQnBOemb+XapNTZEdzf2VRjlnqSqyXGmgNFqCQq+nkzXNeyObnuV6zyvvsBDbmqNceta0BPaV2IJZ4KEFlQw="

language: c

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get -qq update

install:
    - sudo apt-get -qq install libxmlrpc-c3-dev libcurl4-gnutls-dev libpcap-dev libgsl0-dev
    - sudo apt-get -qq install valgrind

script:
    - autoreconf -i
    - ./configure --enable-debug
    - make
    
# Run Tests
after_success:
    - ./src/flowgrindd
    - valgrind --leak-check=full --show-reachable=yes --suppressions=.valgrind.supp ./src/flowgrind -T s=1

# Only watch master and next branch
branches:
  only:
    - master
    - next

notifications:
  email:
    - developer@flowgrind.net

addons:
  # Coverity Scan
  coverity_scan:
    project:
      name: "flowgrind/flowgrind"
      description: "Advanced TCP traffic generator for Linux, FreeBSD, and Mac OS X"
    notification_email: developer@flowgrind.net
    build_command_prepend: autoreconf -i && ./configure --enable-debug
    build_command: make 
    branch_pattern: coverity_scan
